# Generated by Django 4.2.8 on 2026-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group', models.CharField(choices=[('car-care', 'Car Care'), ('home-cleaning', 'Home Cleaning'), ('office-shop-cleaning', 'Office & Shop Cleaning'), ('move-in-out', 'Move In / Move Out'), ('upholstery-fabric', 'Upholstery & Fabric')], max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('requires_address', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['service_group', 'name'],
            },
        ),
    ]
