# Generated by Django 4.2.8 on 2026-02-02 02:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes (e.g., 90)', null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper end of price range (e.g., 77.00)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='subservice',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lower end of price range (e.g., 46.00)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
