# Generated by Django 6.0.1 on 2026-03-06 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='preferred_date',
            new_name='selected_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_window',
        ),
        migrations.AddField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
