# Generated by Django 6.0.1 on 2026-03-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_preferred_date_booking_selected_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
